#!/usr/bin/env bash
# Script to display information about subdomains
# Usage: ./0-world_wide_web domain [subdomain]

# Function to get subdomain information
get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local full_domain="${subdomain}.${domain}"
    
    # Use dig to get DNS information and awk to parse it
    # shellcheck disable=SC2086
    dig "$full_domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -v subdomain_name="$subdomain" '
    {
        if (NF >= 4) {
            record_type = $4
            destination = $5
            print "The subdomain " subdomain_name " is a " record_type " record and points to " destination
        }
    }'
}

# Main script logic
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    # No subdomain specified, show all default subdomains in order
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    # Specific subdomain requested
    get_subdomain_info "$domain" "$subdomain"
fi