#!/usr/bin/env bash
# Configures nginx server with 301 redirect for /redirect_me

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create Hello World page
echo "Hello World!" > /var/www/html/index.html

# Create nginx configuration with redirect
tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    
    server_name _;
    
    location / {
        try_files \$uri \$uri/ =404;
    }
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Start nginx service
service nginx start